export const FETCHING_CHARITIES = 'FETCHING_CHARITIES';
export const FETCH_CHARITIES_SUCCESS = 'FETCH_CHARITIES_SUCCESS';

export const CHARITY_IS_SELECTED = 'CHARITY_IS_SELECTED';
export const AMOUNT_IS_SELECTED = 'AMOUNT_IS_SELECTED';

export const FETCHING_PAYMENTS = 'FETCHING_PAYMENTS';
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS';

export const NEW_PAYMENT_RECEIVED = 'NEW_PAYMENT_RECEIVED';

export const UPDATE_TOTAL_DONATIONS = 'UPDATE_TOTAL_DONATIONS';

export const FORM_VALUES_UPDATED = 'FORM_VALUES_UPDATED';
export const FORM_AMOUNT_VALUE_UPDATED = 'FORM_AMOUNT_VALUE_UPDATED';
export const FORM_ID_VALUE_UPDATED = 'FORM_ID_VALUE_UPDATED';