export const LOAD_INITIAL_FORM_DATA = 'LOAD_INITIAL_FORM_DATA';


export const LOADING_CHARITIES_DATA = 'LOADING_CHARITIES_DATA';
export const RECEIVED_CHARITIES_DATA = 'RECEIVED_CHARITIES_DATA';


export const LOADING_PAYMENTS_DATA = 'LOADING_PAYMENTS_DATA';
export const RECEIVED_PAYMENTS_DATA = 'RECEIVED_PAYMENTS_DATA';

export const RECEIVED_TOTAL_DONATIONS = 'RECEIVED_TOTAL_DONATIONS';

export const SUBMITTING_PAYMENT_DATA = 'SUBMITTING_PAYMENT_DATA';
export const SUBMIT_PAYMENT_DATA_SUCCESS = 'SUBMIT_PAYMENT_DATA_SUCCESS';
export const SUBMIT_PAYMENT_DATA_ERROR = 'SUBMIT_PAYMENT_DATA_ERROR';
